name: Ejecutar PowerShell en Self-Hosted Runner con Snyk

on:
  push:
    branches:
      - main

jobs:
  ejecutar-powershell:
    runs-on: self-hosted
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar dependencias del proyecto
        run: npm install

      - name: Instalar Snyk
        run: npm install -g snyk

      - name: Autenticación con Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Ejecutar script PowerShell
        run: |
          Write-Output "Iniciando script en self-hosted runner"
          Get-Process | Select-Object -First 5
        shell: powershell

      - name: Ejecutar Snyk Test
        run: snyk test
